# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Rahul Madhavan K
tagline:             'now This is perosnal'
description:         'Personal Website'
url:                 http://www.rahulmadhavan.org
baseurl:             /
paginate:            5
sidebar_text:        ''

# Custom vars
version:             1.0.0


# About/contact
author:
  name:              Rahul Madhavan
  url:               http://www.rahulmadhavan.org
  email:             rahulmadhavan21@gmail.com
  github:
    repo:            https://github.com/rahulmadhavan


exclude:
  - CNAME
  - LICENSE.md
  - README.md
  - .gitignore
  - .sass-cache